# Generated by Django 4.2.9 on 2024-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, 'ONE')], max_length=2, verbose_name='Оценка'),
        ),
    ]
